version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db:
    driver: local